version: '3.8'

services:
  app:
    image: 'todo:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/todo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

    ports:
      - "9090:9090"

  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=todo
    ports:
      - "3306:3306"
    volumes:
      - /home/mostafa/data/mysql