server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG